
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { GoogleGenAI } from "@google/genai";

const DesignSystem: React.FC<{ isDarkMode: boolean }> = ({ isDarkMode }) => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState<string | null>(null);
  const [images, setImages] = useState<{ [key: string]: string }>({});

  const generate4KMockup = async (pageName: string, description: string) => {
    setLoading(pageName);
    try {
      // Create instance with the API Key from environment
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      
      const prompt = `A high-fidelity 4K mobile app UI mockup for a platform called "TriYatri". 
      Screen: ${pageName}. 
      Details: ${description}. 
      Style: Clean, modern, community-focused, sage green primary color (#4BA678), 
      using Inter typography, elegant shadows, and a localized feel for North Tripura. 
      The image should look like a professional Dribbble shot.`;

      const response = await ai.models.generateContent({
        model: 'gemini-3-pro-image-preview',
        contents: { parts: [{ text: prompt }] },
        config: {
          imageConfig: {
            aspectRatio: "9:16",
            imageSize: "4K"
          }
        },
      });

      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          const imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          setImages(prev => ({ ...prev, [pageName]: imageUrl }));
        }
      }
    } catch (error) {
      console.error("4K Generation Error:", error);
    } finally {
      setLoading(null);
    }
  };

  const pages = [
    { 
      id: 'home', 
      name: 'Home Screen', 
      desc: 'Map-centric interface with personalized greeting "Hello, User", vehicle selection cards for E-Rickshaw, Auto, and SUV, and a bottom sheet search bar.' 
    },
    { 
      id: 'confirm', 
      name: 'Ride Confirmation', 
      desc: 'Live matching screen with a pulsing sage green indicator, route summary pill, and a soft glassmorphism card showing rider details.' 
    },
    { 
      id: 'profile', 
      name: 'User Profile', 
      desc: 'Clean settings page with a large sage green avatar, verified badges, and toggle-style buttons for switching between Traveller and Rider modes.' 
    }
  ];

  const bgColor = isDarkMode ? 'bg-[#0F111A]' : 'bg-[#F4F6F4]';
  const primaryText = isDarkMode ? 'text-white' : 'text-[#2D2D2D]';

  return (
    <div className={`min-h-full p-6 pb-32 transition-colors duration-700 ${bgColor}`}>
      <header className="mb-10 pt-6">
        <button onClick={() => navigate(-1)} className="mb-4 opacity-40">
          <i className="fa-solid fa-arrow-left"></i> Back
        </button>
        <h1 className={`text-3xl font-black tracking-tighter ${primaryText}`}>4K Visual Assets</h1>
        <p className="text-sm opacity-50 mt-1 italic">Generated by Gemini 3 Pro High-Quality Engine</p>
      </header>

      <div className="space-y-12">
        {pages.map((page) => (
          <div key={page.id} className="space-y-4">
            <div className="flex justify-between items-end">
              <div>
                <h2 className={`text-lg font-bold ${primaryText}`}>{page.name}</h2>
                <p className="text-xs opacity-40 max-w-[250px]">{page.desc}</p>
              </div>
              <button 
                onClick={() => generate4KMockup(page.id, page.desc)}
                disabled={loading === page.id}
                className={`px-4 py-2 rounded-full text-[10px] font-black uppercase tracking-widest bg-[#4BA678] text-white shadow-lg active:scale-95 transition-all ${loading === page.id ? 'opacity-50 animate-pulse' : ''}`}
              >
                {loading === page.id ? 'Rendering 4K...' : 'Generate 4K View'}
              </button>
            </div>

            {images[page.id] ? (
              <div className="relative group overflow-hidden rounded-[40px] shadow-2xl border-4 border-white/10 aspect-[9/16] bg-black/5">
                <img src={images[page.id]} alt={page.name} className="w-full h-full object-cover" />
                <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col items-center justify-center p-8 text-center">
                  <p className="text-white text-xs font-bold mb-4">Click to open full 4K resolution in new tab</p>
                  <button 
                    onClick={() => window.open(images[page.id], '_blank')}
                    className="bg-white text-black px-6 py-3 rounded-full text-[10px] font-black uppercase tracking-widest"
                  >
                    Open Full Image
                  </button>
                </div>
              </div>
            ) : (
              <div className="aspect-[9/16] rounded-[40px] border-2 border-dashed border-[#4BA678]/20 flex flex-col items-center justify-center bg-[#4BA678]/5">
                <i className="fa-solid fa-image text-3xl opacity-10 text-[#4BA678] mb-2"></i>
                <p className="text-[10px] font-bold uppercase tracking-widest opacity-20 text-[#4BA678]">No Render Generated</p>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default DesignSystem;
